### ISSUE TITLE
add canvasapi specification to environment.yml

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/module-progress#15]
need to set canvasapi to the specification that doesn't break _make_dataframe

**Comment by markoprodanovic** [comment]
@alisonmyers  Is it not already in there?
<img width="283" alt="2020-09-24_13-50-52" src="https://user-images.githubusercontent.com/22332030/94199172-41612f80-fe6d-11ea-81ea-8d7cc03e04bf.png">

**Comment by alisonmyers** [comment]
my bad!
