### ISSUE TITLE
Do we still have "admin" run?

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/module-progress#17]
We had an option to run as admin (skips confirmations). Do we still have this? Should we?

**Comment by markoprodanovic** [comment]
It's in there, but it's commented out currently. I personally don't see a need for it. The time saved is negligible, especially now that we don't require instance selection.

With your approval I can remove it completely?

**Comment by alisonmyers** [comment]
Yep, can remove

Best,
Alison

On Sep 25, 2020, at 10:19 AM, Marko Prodanovic <notifications@github.com> wrote:

﻿

It's in there, but it's commented out currently. I personally don't see a need for it. The time saved is negligible, especially now that we don't require instance selection.

With your approval I can remove it completely?

**Comment by markoprodanovic** [comment]
Resolved
