### ISSUE TITLE
[BUG]: Creating environment from environment.yml creates issues

### ISSUE THREAD

**Issue by markoprodanovic** [saud-learning-services/module-progress#7]
* Justin had issue where `canvasapi.exceptions` could not be imported? (#3 )
 * My issue: If I print `module.attributes` in `_make_dataframe`, I get nothing in the "module_progress_test_env" (made from yml) vs data, and complete execution if I run it in "module_progress_env" (original env not from yml)

**Something is wrong with the environment**

**Comment by markoprodanovic** [comment]
Note the second issue listed above may be because accessing JSON used to build objects in **canvasapi** no longer available through **.attributes** syntax? (https://github.com/ucfopen/canvasapi/pull/342)

**Comment by markoprodanovic** [comment]
From depreciation commit:

<img width="1215" alt="Screen Shot 2020-08-04 at 10 24 13 AM" src="https://user-images.githubusercontent.com/22332030/89324792-aef69980-d63c-11ea-8b3e-6017fdd998fc.png">

**Comment by markoprodanovic** [comment]
@alisonmyers this is an important thing to be aware about. A number of our scripts use the **.attributes** syntax (I'd use this regularly to get raw JSON to create dataframes)

We'll need to update the syntax we use to get JSON (for several of our scripts) - _see above for new way_. Either that or we specify canvasapi versions in the .yml file

**Comment by alisonmyers** [comment]
Let's specify the canvasapi version in the .yml for now - new scripts will use the new syntax, and when we have a chance, we can update old scripts to use the new syntax.
