### ISSUE TITLE
[Modification]: Consider what Canvas instances to support?

### ISSUE THREAD

**Issue by markoprodanovic** [saud-learning-services/module-progress#8]
Do we need vars in **.env** for TOKENS in **Canvas**, **Sandbox** and **Instructure**?

**Comment by markoprodanovic** [comment]
.env looks like this but I tend to only use one of these instances? Do we want to support all?

<img width="325" alt="Screen Shot 2020-08-04 at 9 43 45 AM" src="https://user-images.githubusercontent.com/22332030/89320913-03971600-d637-11ea-8a78-df0c67267d6d.png">

**Comment by alisonmyers** [comment]
No need, just use CANVAS_API_TOKEN. sandbox/test are really just for development

**Comment by markoprodanovic** [comment]
Closed by #11
